"""Add godzina_wizyty column

Revision ID: fd18172c135b
Revises: 
Create Date: 2024-11-01 12:40:04.047924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd18172c135b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacjent')
    op.drop_table('lekarz')
    op.drop_table('wizyta')
    with op.batch_alter_table('wizyty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('godzina_wizyty', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wizyty', schema=None) as batch_op:
        batch_op.drop_column('godzina_wizyty')

    op.create_table('wizyta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pacjent_id', sa.INTEGER(), nullable=True),
    sa.Column('lekarz_id', sa.INTEGER(), nullable=True),
    sa.Column('data_wizyty', sa.DATE(), nullable=True),
    sa.Column('opis', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['lekarz_id'], ['lekarz.id'], ),
    sa.ForeignKeyConstraint(['pacjent_id'], ['pacjent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lekarz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('imie', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nazwisko', sa.VARCHAR(length=50), nullable=True),
    sa.Column('specjalizacja', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacjent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('imie', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nazwisko', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pesel', sa.VARCHAR(length=11), nullable=True),
    sa.Column('data_urodzenia', sa.DATE(), nullable=True),
    sa.Column('telefon', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pesel')
    )
    # ### end Alembic commands ###
